from __future__ import annotations

APPLICATION_TABLES = (
    'users',
    'user_passkeys',
    'totp_backup_codes',
    'chats',
    'contacts',
    'chat_members',
    'messages',
    'message_receipts',
    'dialog_keys',
    'dialog_requests',
    'group_invite_requests',
    'group_invite_links',
    'chat_pins',
    'block_list',
    'chat_media',
    'socket_rate_limits',
    'message_reactions',
    'favorite_messages',
    'refresh_tokens',
    'pinned_chats',
    'chat_drafts',
    'link_preview_cache',
    'key_transfer_sessions',
    'push_subscriptions',
    'moderation_reports',
    'moderation_cases',
    'moderation_case_reports',
    'moderation_sanctions',
    'moderation_appeals',
    'moderation_jobs',
    'moderation_user_roles',
    'moderation_audit_log',
    'support_requests',
    'chat_event_state',
    'chat_update_events',
    'schema_migrations',
)


def table_exists(cursor, table_name: str) -> bool:
    row = cursor.execute(
        '''
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = current_schema() AND table_name = ?
        ''',
        (table_name,),
    ).fetchone()
    return row is not None


def table_columns(cursor, table_name: str) -> set[str]:
    rows = cursor.execute(
        '''
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = ?
        ORDER BY ordinal_position
        ''',
        (table_name,),
    ).fetchall()
    return {str(row['column_name']) for row in rows}


def tables_columns(cursor, table_names: list[str] | tuple[str, ...]) -> dict[str, set[str]]:
    normalized_names: list[str] = []
    for raw_name in table_names:
        name = str(raw_name or '').strip()
        if not name:
            continue
        if name in normalized_names:
            continue
        normalized_names.append(name)

    if not normalized_names:
        return {}

    placeholders = ', '.join('?' for _ in normalized_names)
    rows = cursor.execute(
        f'''
        SELECT table_name, column_name
        FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name IN ({placeholders})
        ORDER BY table_name, ordinal_position
        ''',
        tuple(normalized_names),
    ).fetchall()
    result = {name: set() for name in normalized_names}
    for row in rows:
        table_name = str(row['table_name'])
        result.setdefault(table_name, set()).add(str(row['column_name']))
    return result


def table_primary_key_columns(cursor, table_name: str) -> list[str]:
    rows = cursor.execute(
        '''
        SELECT kcu.column_name
        FROM information_schema.table_constraints AS tc
        JOIN information_schema.key_column_usage AS kcu
          ON tc.constraint_name = kcu.constraint_name
         AND tc.table_schema = kcu.table_schema
        WHERE tc.table_schema = current_schema()
          AND tc.table_name = ?
          AND tc.constraint_type = 'PRIMARY KEY'
        ORDER BY kcu.ordinal_position
        ''',
        (table_name,),
    ).fetchall()
    return [str(row['column_name']) for row in rows]


def chat_pins_supports_multiple(cursor) -> bool:
    return table_primary_key_columns(cursor, 'chat_pins') == ['chat_id', 'message_id']


def socket_rate_limits_support_event_scope(cursor) -> bool:
    columns = table_columns(cursor, 'socket_rate_limits')
    if not columns or 'event_name' not in columns:
        return False
    return table_primary_key_columns(cursor, 'socket_rate_limits') == ['user_id', 'event_name']


def ensure_base_schema(conn) -> None:
    conn.executescript(
        '''
        CREATE TABLE IF NOT EXISTS users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            public_key TEXT UNIQUE NOT NULL,
            username TEXT UNIQUE NOT NULL,
            display_name TEXT NOT NULL,
            bio TEXT NOT NULL DEFAULT '',
            is_public INTEGER NOT NULL DEFAULT 1,
            auto_decline_requests INTEGER NOT NULL DEFAULT 0,
            mute_dialog_requests INTEGER NOT NULL DEFAULT 0,
            hide_online_status INTEGER NOT NULL DEFAULT 0,
            last_seen TEXT,
            avatar_url TEXT DEFAULT NULL,
            avatar_visibility TEXT DEFAULT 'all',
            group_invite_privacy TEXT NOT NULL DEFAULT 'all',
            is_online INTEGER DEFAULT 0,
            totp_secret TEXT,
            totp_enabled_at TIMESTAMP,
            login_vault TEXT,
            language TEXT NOT NULL DEFAULT 'ru',
            client_preferences TEXT NOT NULL DEFAULT '{}'
        );

        CREATE TABLE IF NOT EXISTS chats (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            chat_id TEXT UNIQUE NOT NULL,
            chat_name TEXT NOT NULL DEFAULT 'New Chat',
            chat_type TEXT NOT NULL DEFAULT 'direct',
            chat_description TEXT NOT NULL DEFAULT '',
            chat_avatar_url TEXT DEFAULT NULL,
            created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            group_perm_send_messages INTEGER NOT NULL DEFAULT 1,
            group_perm_send_media INTEGER NOT NULL DEFAULT 1,
            group_perm_add_members INTEGER NOT NULL DEFAULT 0,
            group_perm_pin_messages INTEGER NOT NULL DEFAULT 0,
            group_perm_change_info INTEGER NOT NULL DEFAULT 0,
            group_slow_mode_seconds INTEGER NOT NULL DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS contacts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            contact_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            chat_id TEXT NOT NULL REFERENCES chats(chat_id) ON DELETE CASCADE,
            label TEXT,
            contact_display_name TEXT,
            contact_username TEXT,
            UNIQUE(user_id, contact_id)
        );

        CREATE TABLE IF NOT EXISTS chat_members (
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            chat_id TEXT NOT NULL REFERENCES chats(chat_id) ON DELETE CASCADE,
            role TEXT NOT NULL DEFAULT 'member',
            joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            added_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            PRIMARY KEY (user_id, chat_id)
        );

        CREATE TABLE IF NOT EXISTS messages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            chat_id TEXT NOT NULL REFERENCES chats(chat_id) ON DELETE CASCADE,
            sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            receiver_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            message TEXT NOT NULL,
            is_read INTEGER NOT NULL DEFAULT 0,
            read_at TIMESTAMP DEFAULT NULL,
            voice_listened_by_receiver INTEGER NOT NULL DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            is_edited INTEGER DEFAULT 0,
            message_type TEXT DEFAULT 'text',
            deleted_by_sender INTEGER DEFAULT 0,
            deleted_by_receiver INTEGER DEFAULT 0,
            reply_to_id BIGINT REFERENCES messages(id) ON DELETE SET NULL,
            forward_from_name TEXT DEFAULT NULL,
            forward_from_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            edit_count INTEGER DEFAULT 0,
            is_delivered INTEGER NOT NULL DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS message_receipts (
            message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            is_delivered INTEGER NOT NULL DEFAULT 0,
            delivered_at TIMESTAMP,
            is_read INTEGER NOT NULL DEFAULT 0,
            read_at TIMESTAMP,
            voice_listened INTEGER NOT NULL DEFAULT 0,
            deleted_for_user INTEGER NOT NULL DEFAULT 0,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (message_id, user_id)
        );

        CREATE TABLE IF NOT EXISTS dialog_keys (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            key_value TEXT UNIQUE NOT NULL,
            creator_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            used INTEGER NOT NULL DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS dialog_requests (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            receiver_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            status TEXT NOT NULL DEFAULT 'pending',
            timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(sender_id, receiver_id)
        );

        CREATE TABLE IF NOT EXISTS group_invite_requests (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            chat_id TEXT NOT NULL REFERENCES chats(chat_id) ON DELETE CASCADE,
            inviter_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            invitee_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            status TEXT NOT NULL DEFAULT 'pending',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            responded_at TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS group_invite_links (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            chat_id TEXT NOT NULL REFERENCES chats(chat_id) ON DELETE CASCADE,
            token TEXT NOT NULL UNIQUE,
            created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            max_uses INTEGER DEFAULT NULL,
            uses_count INTEGER NOT NULL DEFAULT 0,
            expires_at TIMESTAMP DEFAULT NULL,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS chat_pins (
            chat_id TEXT NOT NULL REFERENCES chats(chat_id) ON DELETE CASCADE,
            message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
            message_content TEXT,
            pinned_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
            sender_pub TEXT,
            pinned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (chat_id, message_id)
        );

        CREATE TABLE IF NOT EXISTS block_list (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            blocker_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            blocked_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(blocker_id, blocked_id)
        );

        CREATE TABLE IF NOT EXISTS chat_media (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            chat_id TEXT NOT NULL REFERENCES chats(chat_id) ON DELETE CASCADE,
            uploader_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            storage_name TEXT NOT NULL UNIQUE,
            original_name TEXT,
            mime_type TEXT,
            size BIGINT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS socket_rate_limits (
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            event_name TEXT NOT NULL,
            window_started_at BIGINT NOT NULL,
            event_count INTEGER NOT NULL DEFAULT 0,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (user_id, event_name)
        );

        CREATE TABLE IF NOT EXISTS message_reactions (
            message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
            chat_id TEXT NOT NULL REFERENCES chats(chat_id) ON DELETE CASCADE,
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            emoji TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY(message_id, user_id)
        );

        CREATE TABLE IF NOT EXISTS favorite_messages (
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            chat_id TEXT NOT NULL REFERENCES chats(chat_id) ON DELETE CASCADE,
            message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
            message_content TEXT,
            sender_pub TEXT,
            favorited_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY(user_id, message_id)
        );

        CREATE TABLE IF NOT EXISTS refresh_tokens (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            token_hash TEXT NOT NULL UNIQUE,
            family_id TEXT NOT NULL,
            expires_at BIGINT NOT NULL,
            revoked_at BIGINT,
            created_at BIGINT NOT NULL,
            last_used_at BIGINT,
            user_agent TEXT,
            ip TEXT
        );

        CREATE TABLE IF NOT EXISTS pinned_chats (
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            chat_id TEXT NOT NULL REFERENCES chats(chat_id) ON DELETE CASCADE,
            pin_order INTEGER NOT NULL DEFAULT 0,
            pinned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (user_id, chat_id)
        );

        CREATE TABLE IF NOT EXISTS chat_drafts (
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            chat_id TEXT NOT NULL REFERENCES chats(chat_id) ON DELETE CASCADE,
            draft_text TEXT NOT NULL,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (user_id, chat_id)
        );

        CREATE TABLE IF NOT EXISTS link_preview_cache (
            normalized_url TEXT PRIMARY KEY,
            schema_version INTEGER NOT NULL,
            expires_at BIGINT NOT NULL,
            has_meta INTEGER NOT NULL DEFAULT 0,
            payload_json TEXT NOT NULL,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS user_passkeys (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            credential_id TEXT NOT NULL UNIQUE,
            credential_public_key TEXT NOT NULL,
            sign_count BIGINT NOT NULL DEFAULT 0,
            transports TEXT,
            label TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            last_used_at TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS totp_backup_codes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            code_hash TEXT NOT NULL,
            used_at TIMESTAMP DEFAULT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS key_transfer_sessions (
            id TEXT PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            receiver_public_jwk TEXT NOT NULL,
            sender_public_jwk TEXT,
            encrypted_private_key TEXT,
            iv TEXT,
            status TEXT NOT NULL DEFAULT 'pending',
            created_at BIGINT NOT NULL,
            expires_at BIGINT NOT NULL,
            submitted_at BIGINT,
            claimed_at BIGINT
        );

        CREATE TABLE IF NOT EXISTS key_transfer_login_sessions (
            id TEXT PRIMARY KEY,
            receiver_public_jwk TEXT NOT NULL,
            sender_public_jwk TEXT,
            encrypted_private_key TEXT,
            iv TEXT,
            submitted_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            status TEXT NOT NULL DEFAULT 'pending',
            created_at BIGINT NOT NULL,
            expires_at BIGINT NOT NULL,
            submitted_at BIGINT,
            claimed_at BIGINT
        );

        CREATE TABLE IF NOT EXISTS push_subscriptions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            endpoint TEXT NOT NULL UNIQUE,
            p256dh TEXT NOT NULL,
            auth TEXT NOT NULL,
            user_agent TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            last_success_at TIMESTAMP,
            last_failure_at TIMESTAMP,
            failure_count INTEGER NOT NULL DEFAULT 0,
            is_active INTEGER NOT NULL DEFAULT 1
        );

        CREATE TABLE IF NOT EXISTS moderation_reports (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reporter_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            target_type TEXT NOT NULL,
            target_id TEXT NOT NULL,
            message_id BIGINT REFERENCES messages(id) ON DELETE SET NULL,
            reason_code TEXT NOT NULL,
            subreason_code TEXT,
            comment TEXT,
            status TEXT NOT NULL DEFAULT 'received',
            idempotency_key TEXT NOT NULL,
            source_ip TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS moderation_cases (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            case_type TEXT NOT NULL,
            subject_type TEXT NOT NULL,
            subject_id TEXT NOT NULL,
            state TEXT NOT NULL DEFAULT 'open',
            priority INTEGER NOT NULL DEFAULT 3,
            risk_score REAL NOT NULL DEFAULT 0.0,
            confidence REAL NOT NULL DEFAULT 0.0,
            decision_source TEXT NOT NULL DEFAULT 'rules',
            decision_reason TEXT,
            assigned_moderator_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS moderation_case_reports (
            case_id BIGINT NOT NULL REFERENCES moderation_cases(id) ON DELETE CASCADE,
            report_id BIGINT NOT NULL REFERENCES moderation_reports(id) ON DELETE CASCADE,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY(case_id, report_id)
        );

        CREATE TABLE IF NOT EXISTS moderation_sanctions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            case_id BIGINT REFERENCES moderation_cases(id) ON DELETE SET NULL,
            subject_type TEXT NOT NULL,
            subject_id TEXT NOT NULL,
            action_type TEXT NOT NULL,
            reason_code TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'active',
            created_by TEXT NOT NULL,
            starts_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            expires_at TIMESTAMP,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS moderation_appeals (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sanction_id BIGINT NOT NULL REFERENCES moderation_sanctions(id) ON DELETE CASCADE,
            appellant_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            text TEXT,
            state TEXT NOT NULL DEFAULT 'submitted',
            reviewer_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            resolution_note TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            resolved_at TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS moderation_jobs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            report_id BIGINT NOT NULL UNIQUE REFERENCES moderation_reports(id) ON DELETE CASCADE,
            status TEXT NOT NULL DEFAULT 'pending',
            attempts INTEGER NOT NULL DEFAULT 0,
            available_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            locked_at TIMESTAMP,
            locked_by TEXT,
            last_error TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS moderation_user_roles (
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            role TEXT NOT NULL,
            granted_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            granted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (user_id, role)
        );

        CREATE TABLE IF NOT EXISTS moderation_audit_log (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            actor_type TEXT NOT NULL,
            actor_id TEXT NOT NULL,
            action TEXT NOT NULL,
            entity_type TEXT NOT NULL,
            entity_id TEXT NOT NULL,
            details_json TEXT NOT NULL DEFAULT '{}',
            trace_id TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS support_requests (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            created_by_username TEXT,
            contact_email TEXT,
            contact_handle TEXT,
            source_page TEXT NOT NULL DEFAULT 'unknown',
            category TEXT NOT NULL DEFAULT 'general',
            subject TEXT NOT NULL,
            body TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'open',
            priority INTEGER NOT NULL DEFAULT 3,
            assigned_moderator_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            resolution_note TEXT,
            meta_json TEXT NOT NULL DEFAULT '{}',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            resolved_at TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS chat_event_state (
            chat_id TEXT PRIMARY KEY REFERENCES chats(chat_id) ON DELETE CASCADE,
            last_pts BIGINT NOT NULL DEFAULT 0,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS chat_update_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            event_id TEXT NOT NULL UNIQUE,
            event_type TEXT NOT NULL,
            server_ts TEXT NOT NULL,
            chat_id TEXT NOT NULL REFERENCES chats(chat_id) ON DELETE CASCADE,
            chat_pts BIGINT NOT NULL,
            request_id TEXT,
            payload_json TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS schema_migrations (
            version INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_unique ON users(username);
        CREATE INDEX IF NOT EXISTS idx_contacts_user_id ON contacts(user_id);
        CREATE INDEX IF NOT EXISTS idx_contacts_user_chat_id ON contacts(user_id, chat_id);
        CREATE INDEX IF NOT EXISTS idx_contacts_user_chat_contact ON contacts(user_id, chat_id, contact_id);
        CREATE INDEX IF NOT EXISTS idx_contacts_contact_user ON contacts(contact_id, user_id);
        CREATE INDEX IF NOT EXISTS idx_chat_members_chat_user ON chat_members(chat_id, user_id);
        CREATE INDEX IF NOT EXISTS idx_chat_members_user_chat ON chat_members(user_id, chat_id);
        CREATE INDEX IF NOT EXISTS idx_messages_chat_id ON messages(chat_id);
        CREATE INDEX IF NOT EXISTS idx_messages_chat_id_id ON messages(chat_id, id);
        CREATE INDEX IF NOT EXISTS idx_messages_chat_sender_deleted_id ON messages(chat_id, sender_id, deleted_by_sender, id DESC);
        CREATE INDEX IF NOT EXISTS idx_messages_chat_receiver_deleted_id ON messages(chat_id, receiver_id, deleted_by_receiver, id DESC);
        CREATE INDEX IF NOT EXISTS idx_messages_receiver_delivery ON messages(receiver_id, is_delivered);
        CREATE INDEX IF NOT EXISTS idx_messages_chat_receiver_read ON messages(chat_id, receiver_id, is_read, deleted_by_receiver);
        CREATE INDEX IF NOT EXISTS idx_messages_receiver_read_deleted_chat ON messages(receiver_id, is_read, deleted_by_receiver, chat_id);
        CREATE INDEX IF NOT EXISTS idx_message_receipts_message_id ON message_receipts(message_id);
        CREATE INDEX IF NOT EXISTS idx_message_receipts_user_unread ON message_receipts(user_id, is_read, deleted_for_user);
        CREATE INDEX IF NOT EXISTS idx_message_receipts_user_deleted_message ON message_receipts(user_id, deleted_for_user, message_id DESC);
        CREATE INDEX IF NOT EXISTS idx_message_receipts_user_deleted_read_message ON message_receipts(user_id, deleted_for_user, is_read, message_id DESC);
        CREATE INDEX IF NOT EXISTS idx_message_receipts_user_deleted_delivered_message ON message_receipts(user_id, deleted_for_user, is_delivered, message_id DESC);
        CREATE INDEX IF NOT EXISTS idx_dialog_keys_key_value ON dialog_keys(key_value);
        CREATE INDEX IF NOT EXISTS idx_dialog_requests_receiver ON dialog_requests(receiver_id);
        CREATE INDEX IF NOT EXISTS idx_dialog_requests_receiver_status_sender ON dialog_requests(receiver_id, status, sender_id);
        CREATE INDEX IF NOT EXISTS idx_group_invite_requests_invitee_status_created
            ON group_invite_requests(invitee_user_id, status, created_at DESC);
        CREATE INDEX IF NOT EXISTS idx_group_invite_requests_chat_invitee_status
            ON group_invite_requests(chat_id, invitee_user_id, status);
        CREATE INDEX IF NOT EXISTS idx_block_list_blocker_id ON block_list(blocker_id);
        CREATE INDEX IF NOT EXISTS idx_block_list_blocked_id ON block_list(blocked_id);
        CREATE INDEX IF NOT EXISTS idx_chat_media_chat_id ON chat_media(chat_id);
        CREATE INDEX IF NOT EXISTS idx_socket_rate_limits_updated_at ON socket_rate_limits(updated_at);
        CREATE INDEX IF NOT EXISTS idx_message_reactions_chat_message ON message_reactions(chat_id, message_id);
        CREATE INDEX IF NOT EXISTS idx_message_reactions_user_id ON message_reactions(user_id);
        CREATE INDEX IF NOT EXISTS idx_favorite_messages_user_chat_favorited ON favorite_messages(user_id, chat_id, favorited_at DESC, message_id DESC);
        CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens(user_id);
        CREATE INDEX IF NOT EXISTS idx_refresh_tokens_family ON refresh_tokens(family_id);
        CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires ON refresh_tokens(expires_at);
        CREATE INDEX IF NOT EXISTS idx_pinned_chats_user_id ON pinned_chats(user_id, pin_order);
        CREATE INDEX IF NOT EXISTS idx_chat_drafts_user_updated_at ON chat_drafts(user_id, updated_at DESC);
        CREATE INDEX IF NOT EXISTS idx_link_preview_cache_expires_at ON link_preview_cache(expires_at);
        CREATE INDEX IF NOT EXISTS idx_link_preview_cache_updated_at ON link_preview_cache(updated_at DESC);
        CREATE INDEX IF NOT EXISTS idx_chat_pins_chat_pinned_at ON chat_pins(chat_id, pinned_at DESC, message_id DESC);
        CREATE INDEX IF NOT EXISTS idx_user_passkeys_user_id ON user_passkeys(user_id, created_at DESC);
        CREATE INDEX IF NOT EXISTS idx_key_transfer_sessions_user_created ON key_transfer_sessions(user_id, created_at DESC);
        CREATE INDEX IF NOT EXISTS idx_key_transfer_sessions_expires ON key_transfer_sessions(expires_at);
        CREATE INDEX IF NOT EXISTS idx_key_transfer_login_sessions_expires ON key_transfer_login_sessions(expires_at);
        CREATE INDEX IF NOT EXISTS idx_key_transfer_login_sessions_submitter ON key_transfer_login_sessions(submitted_by_user_id, created_at DESC);
        CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user_id ON push_subscriptions(user_id);
        CREATE INDEX IF NOT EXISTS idx_push_subscriptions_active_user_id ON push_subscriptions(user_id, is_active);
        CREATE INDEX IF NOT EXISTS idx_push_subscriptions_updated_at ON push_subscriptions(updated_at DESC);
        CREATE UNIQUE INDEX IF NOT EXISTS idx_moderation_reports_idempotency ON moderation_reports(reporter_user_id, idempotency_key);
        CREATE INDEX IF NOT EXISTS idx_moderation_reports_target_created ON moderation_reports(target_type, target_id, created_at DESC);
        CREATE INDEX IF NOT EXISTS idx_moderation_reports_status_created ON moderation_reports(status, created_at DESC);
        CREATE INDEX IF NOT EXISTS idx_moderation_cases_state_priority ON moderation_cases(state, priority, created_at DESC);
        CREATE INDEX IF NOT EXISTS idx_moderation_cases_subject ON moderation_cases(subject_type, subject_id, created_at DESC);
        CREATE INDEX IF NOT EXISTS idx_moderation_sanctions_subject_status ON moderation_sanctions(subject_type, subject_id, status, expires_at);
        CREATE INDEX IF NOT EXISTS idx_moderation_sanctions_subject_status_action_created ON moderation_sanctions(subject_type, subject_id, status, action_type, created_at DESC);
        CREATE INDEX IF NOT EXISTS idx_moderation_sanctions_case_id ON moderation_sanctions(case_id);
        CREATE INDEX IF NOT EXISTS idx_moderation_appeals_state_created ON moderation_appeals(state, created_at DESC);
        CREATE INDEX IF NOT EXISTS idx_moderation_appeals_sanction ON moderation_appeals(sanction_id);
        CREATE INDEX IF NOT EXISTS idx_moderation_jobs_status_available ON moderation_jobs(status, available_at, created_at);
        CREATE INDEX IF NOT EXISTS idx_moderation_jobs_report_id ON moderation_jobs(report_id);
        CREATE INDEX IF NOT EXISTS idx_moderation_user_roles_role_user ON moderation_user_roles(role, user_id);
        CREATE INDEX IF NOT EXISTS idx_moderation_audit_entity_time ON moderation_audit_log(entity_type, entity_id, created_at DESC);
        CREATE INDEX IF NOT EXISTS idx_moderation_audit_trace ON moderation_audit_log(trace_id);
        CREATE INDEX IF NOT EXISTS idx_support_requests_status_created ON support_requests(status, created_at DESC);
        CREATE INDEX IF NOT EXISTS idx_support_requests_status_priority_created ON support_requests(status, priority, created_at DESC);
        CREATE INDEX IF NOT EXISTS idx_support_requests_user_created ON support_requests(created_by_user_id, created_at DESC);
        CREATE INDEX IF NOT EXISTS idx_support_requests_category_created ON support_requests(category, created_at DESC);
        CREATE UNIQUE INDEX IF NOT EXISTS idx_chat_update_events_chat_pts_unique ON chat_update_events(chat_id, chat_pts);
        CREATE INDEX IF NOT EXISTS idx_chat_update_events_chat_pts_desc ON chat_update_events(chat_id, chat_pts DESC);
        CREATE INDEX IF NOT EXISTS idx_chat_update_events_event_id ON chat_update_events(event_id);
        CREATE INDEX IF NOT EXISTS idx_users_lower_username ON users(LOWER(username));
        CREATE INDEX IF NOT EXISTS idx_users_lower_display_name ON users(LOWER(display_name));
        CREATE INDEX IF NOT EXISTS idx_totp_backup_codes_user_id ON totp_backup_codes(user_id);
        CREATE UNIQUE INDEX IF NOT EXISTS idx_group_invite_links_token ON group_invite_links(token);
        CREATE INDEX IF NOT EXISTS idx_group_invite_links_chat_active ON group_invite_links(chat_id, is_active);
        '''
    )
    conn.commit()
